#  docker-compose up -d

version: "3"

services:
  postgres:
    image: postgres
    container_name: myproject
    environment:
      POSTGRES_USER: "${DB_USER_ID}"
      POSTGRES_PASSWORD: "${DB_USER_PASSWORD}"
    ports:
      - '5432:5432'
    volumes:
      - ${POSTGRES_HOME_DIR}/myproject:/var/lib/postgresql/data