version: "3"
#services:
#  db:
#    image: mysql:latest
#    container_name: docker-mysql
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: 'qwerqwer123'
#    command:
#      - --character-set-server=utf8mb4
#      - --collation-server=utf8mb4_unicode_ci
#    volumes:
#      - E:\docker/wool/Dev/db_data_docker:/var/lib/mysql
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: "${DB_USER_ID}"
      POSTGRES_PASSWORD: "${DB_USER_PASSWORD}"
    ports:
      - '5432:5432'
    volumes:
      - ${POSTGRES_HOME_DIR}/postgres:/var/lib/postgresql/data