
server:
  port: 3030

## database 접속 설정
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project
    username: admin
    password: admin

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true

        ddl-auto: update

    database-platform: org.hibernate.dialect.PostgreSQLDialect