## http://mageddo.com/tools/yaml-converter

server:
  port: 3030

## database 접속 설정
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my_project
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.PostgreSQLDialect