
server:
  port: 3030

## database 접속 설정
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdata
    username: kewon
    password: pass

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true

        ddl-auto: update